# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blue Button API
description: > # this means to ignore newlines until "baseurl:"
  The Blue Button service provides a developer-friendly, standards-based data API that enables beneficiaries to connect their Medicare claims data to the applications, services, and research programs they trust.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# tealium_env: "dev"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  load_paths:
      - _sass
      - node_modules
exclude:
  - .gitignore
  - README.md
  - LICENSE.txt
  - RELEASE.txt
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .gitattributes
  - package.json
  - Jenkinsfile
  - ops

# Configure the `_plugins/api_codings.rb` plugin. Note that you can run
# `bundle exec jekyll serve --verbose` to get debug output from that plugin.
codebooks:
  layout: codeset.html
  xml_files:
    # Need to get full XML files included here, once CBBI-343 is complete.
    - _codebooks/codebook-mbsf-abcd-trimmed.xml
    - _codebooks/codebook-ffs-claims-trimmed.xml
