# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CMS Blue Button API
description: > # this means to ignore newlines until "baseurl:"
  The CMS Blue Button API enables beneficiaries to connect their Medicare claims data to the applications, services, and research programs they trust.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# permalink: /blog/:title/
permalink: /blog/:title
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  load_paths:
      - _sass
      - node_modules
exclude:
  - .gitignore
  - README.md
  - LICENSE.txt
  - RELEASE.txt
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .gitattributes
  - package.json
  - Jenkinsfile
  - ops

include: ["_pages"]

exclude: ["assets/bluebutton-ig/"]

# Settings for RSS Feed for Blog
name: Blue Button 2.0 Blog
# the next two values are defined above so we are changing the keys.
blog_description: How-to guides, code recipes and other useful content related to Blue Button 2.0 API
blog_url: https://bluebutton.cms.gov

# S3 appears to require blog templates to append ".html" to files.
# Define "use_dot_html" = true in environment _config file
# default should be false i.e. not defined
# use_dot_html: true

# Configure the `_plugins/api_codings.rb` plugin. Note that you can run
# `bundle exec jekyll serve --verbose` to get debug output from that plugin.
codebooks:
  layout: variable.html
  xml_files:
    # These files are produced by the
    # `bluebutton-data-model.git/bluebutton-data-model-codebook-extractor`
    # project, and copied by hand to this project, as needed.
    - _codebooks/codebook-mbsf-abd.xml
    - _codebooks/codebook-ffs-claims.xml
    - _codebooks/codebook-pde.xml
