#!/bin/bash

set -e

yum install -y nginx

# Install nginx.conf
cat > /etc/nginx/nginx.conf << EOM
${nginx_conf}
EOM

chmod 0755 /var/log/nginx

# Restart nginx
service nginx restart;

# Configure Splunk
sed -i 's/REPLACE-WITH-APP-NAME/BB-STATIC-${env}/g' \
  /opt/splunkforwarder/etc/system/local/deploymentclient.conf

/opt/splunkforwarder/bin/splunk stop
/opt/splunkforwarder/bin/splunk clone-prep-clear-config
/opt/splunkforwarder/bin/splunk start
