ARG RUBY_VERSION

FROM ruby:${RUBY_VERSION}

RUN gem install --no-document bundler:2.2.16 && \
    curl -L -o get-pip.py https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    pip install awscli