#!groovy
def aws_creds = 'cbj-deploy'

pipeline {
  agent any

  parameters {
    string(
      name: 'GIT_VERSION',
      defaultValue: '*/master',
      description: 'The branch, tag or commit to deploy.'
    )
    booleanParam(
      defaultValue: false,
      description: 'When true, deploy to both TEST and PROD environments.',
      name: 'DEPLOY_PROD'
    )
  }

  stages {
    stage('Clear') {
      steps {
        deleteDir()
      }
    }

    stage('Checkout') {
      steps {
        checkout([
            $class: 'GitSCM',
            branches: [[name: "${params.GIT_VERSION}"]],
            userRemoteConfigs: [[
              url: 'https://github.com/CMSgov/bluebutton-site-static.git'
            ]]
        ])
      }
    }

    stage('Install') {
      steps {
        sh '''
          rbenv local 2.3.0
          gem install  --no-ri --no-rdoc bundler
          bundle install
          '''
      }
    }

    stage('Build') {
      steps {
        parallel (
          "build test": {
            script {
              def site_folder = "_site-test"
              sh """
                bundle exec jekyll build --config _config.yml -d ./${site_folder}
              """
            }
          },
          "build prod": {
            script {
              def site_folder = "_site"
              sh """
                bundle exec jekyll build --config _config.yml -d ./${site_folder}
              """
            }
          }
        )
      }
    }

    stage('Deploy to Test') {
      steps {
        withAwsCli(credentialsId: aws_creds, defaultRegion: 'us-east-1') {
          sh """
            aws s3 sync --acl public-read --delete ./_site-test/ s3://test.bluebutton.cms.gov
          """
        }
      }
    }

    stage('Deploy to Prod') {
      steps {
        withAwsCli(credentialsId: aws_creds, defaultRegion: 'us-east-1') {
          sh """
            aws s3 sync --acl public-read --delete ./_site/ s3://bluebutton.cms.gov
          """
        }
      }
      when {
        expression {
          params.DEPLOY_PROD == true
        }
      }
    }
  }
}
